/******************************************************************************
Project     : New Message System
Description : Test Program
Programmer  : Baccan Matteo
******************************************************************************/

* ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
PROCEDURE main()
* ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
LOCAL LogicalValue := .T.
LOCAL GetList      := {}

CLS

@ 0,0 SAY "LogicalValue" GET LogicalValue PICTURE "Y"

READ

CLS

? LogicalValue

RETURN
